import * as _pipe from 'ramda/src/pipe';
import * as _propOr from 'ramda/src/propOr';
import * as _keys from 'ramda/src/keys';
import * as _values from 'ramda/src/values';
import * as _map from 'ramda/src/map';
import * as _fromPairs from 'ramda/src/fromPairs';
import * as _toPairs from 'ramda/src/toPairs';
import * as _chain from 'ramda/src/chain';
import * as _reduce from 'ramda/src/reduce';
import * as _prop from 'ramda/src/prop';
import * as _pick from 'ramda/src/pick';
import * as _pathOr from 'ramda/src/pathOr';
import * as _addIndex from 'ramda/src/addIndex';
import * as _zip from 'ramda/src/zip';
import * as _path from 'ramda/src/path';
import * as _update from 'ramda/src/update';
import * as _equals from 'ramda/src/equals';
import * as _contains from 'ramda/src/contains';
import * as _when from 'ramda/src/when';
import * as _always from 'ramda/src/always';
import * as _identity from 'ramda/src/identity';
import * as _splitEvery from 'ramda/src/splitEvery';
import * as _flatten from 'ramda/src/flatten';

export const pipe = _pipe;
export const propOr = _propOr;
export const keys = _keys;
export const values = _values;
export const map = _map;
export const fromPairs = _fromPairs;
export const toPairs = _toPairs;
export const chain = _chain;
export const reduce = _reduce;
export const prop = _prop;
export const pick = _pick;
export const pathOr = _pathOr;
export const addIndex = _addIndex;
export const zip = _zip;
export const path = _path;
export const update = _update;
export const equals = _equals;
export const contains = _contains;
export const when = _when;
export const always = _always;
export const identity = _identity;
export const splitEvery = _splitEvery;
export const flatten = _flatten;
