import {
    HlcClrCheckboxesComponent,
    HlcClrCheckboxesModule,
    HlcClrDateComponent,
    HlcClrDateModule,
    HlcClrDateRangeComponent,
    HlcClrDateRangeModule,
    HlcClrDateTimeComponent,
    HlcClrDateTimeModule,
    HlcClrDisplayComponent,
    HlcClrDisplayModule,
    HlcClrMaskComponent,
    HlcClrMaskModule,
    HlcClrMultiSelectComponent,
    HlcClrMultiSelectModule,
    HlcClrOptionsComponent,
    HlcClrOptionsModule,
    HlcClrPairsListComponent,
    HlcClrPairsListModule,
    HlcClrPasswordComponent,
    HlcClrPasswordModule,
    HlcClrPhoneComponent,
    HlcClrPhoneModule,
    HlcClrSelectComponent,
    HlcClrSelectModule,
    HlcClrTagsComponent,
    HlcClrTagsModule,
    HlcClrTextAreaComponent,
    HlcClrTextAreaModule,
    HlcClrTextComponent,
    HlcClrTextModule,
    HlcClrToggleComponent,
    HlcClrToggleModule,
    HlcClrTypeaheadComponent,
    HlcClrTypeaheadModule,
    HlcClrMonthYearSelectModule,
    HlcClrMonthYearSelectComponent
} from '@ng-holistic/clr-controls';

/**
 * Predefined set of controls based on clarity design system which could be possible generated on form layout.
 */
export const clrFieldsLayoutMap = {
    TextField: HlcClrTextComponent,
    TextAreaField: HlcClrTextAreaComponent,
    SelectField: HlcClrSelectComponent,
    DateField: HlcClrDateComponent,
    ToggleField: HlcClrToggleComponent,
    OptionsField: HlcClrOptionsComponent,
    CheckboxesField: HlcClrCheckboxesComponent,
    DateTimeField: HlcClrDateTimeComponent,
    DateRangeField: HlcClrDateRangeComponent,
    MaskField: HlcClrMaskComponent,
    PhoneField: HlcClrPhoneComponent,
    PasswordField: HlcClrPasswordComponent,
    PairsListField: HlcClrPairsListComponent,
    TypeaheadField: HlcClrTypeaheadComponent,
    TagsField: HlcClrTagsComponent,
    MultiSelectField: HlcClrMultiSelectComponent,
    DisplayField: HlcClrDisplayComponent,
    MonthYearSelectField: HlcClrMonthYearSelectComponent
};

export const clrFieldsLayoutComponents = [
    HlcClrTextComponent,
    HlcClrTextAreaComponent,
    HlcClrSelectComponent,
    HlcClrDateComponent,
    HlcClrToggleComponent,
    HlcClrOptionsComponent,
    HlcClrCheckboxesComponent,
    HlcClrDateTimeComponent,
    HlcClrDateRangeComponent,
    HlcClrMaskComponent,
    HlcClrPhoneComponent,
    HlcClrPasswordComponent,
    HlcClrPairsListComponent,
    HlcClrTypeaheadComponent,
    HlcClrTagsComponent,
    HlcClrMultiSelectComponent,
    HlcClrDisplayComponent,
    HlcClrMonthYearSelectComponent
];

export const clrFieldsLayoutModules = [
    HlcClrTextModule,
    HlcClrTextAreaModule,
    HlcClrSelectModule,
    HlcClrDateModule,
    HlcClrToggleModule,
    HlcClrOptionsModule,
    HlcClrCheckboxesModule,
    HlcClrDateTimeModule,
    HlcClrDateRangeModule,
    HlcClrMaskModule,
    HlcClrPhoneModule,
    HlcClrPasswordModule,
    HlcClrPairsListModule,
    HlcClrTypeaheadModule,
    HlcClrTagsModule,
    HlcClrMultiSelectModule,
    HlcClrDisplayModule,
    HlcClrMonthYearSelectModule
];
